.TH "HQX" 1 "2021-11-21" "" "User Commands"
.
.SH NAME
\fBhqx\fR \- high quality upscaling program for pixel-art
.
.SH SUMMARY
.SY hqx
[\-s \fISCALE\fR]
.I INPUT OUTPUT
.YS
.
.SH DESCRIPTION
\fBhqx\fR is a high quality pixel-art upscaling program, utilizing
hqx, one of the pixel art scaling algorithms developed by Maxim Stepin.
.
.SH OPTIONS
.TP
\fB\-s\fR \fISCALE\fR
Scale factor to use. Supported values are \fB2\fR, \fB3\fR and \fB4\fR.
If omitted, defaults to 4.
